// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'ap-southeast-1:f65629f7-d05b-4ade-9cca-9752b82148cd',
    'aws_cognito_region': 'ap-southeast-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'nuscloudca-hosting-mobilehub-726174774',
    'aws_content_delivery_bucket_region': 'ap-southeast-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dbikd0czq0mea.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'ap-southeast-1',
    'aws_dynamodb_table_schemas': [{"tableName":"nuscloudca-mobilehub-726174774-postdir","attributes":[{"name":"username","type":"S"},{"name":"timestamp","type":"N"},{"name":"description","type":"S"},{"name":"likes","type":"N"},{"name":"postid","type":"S"}],"indexes":[],"region":"ap-southeast-1","hashKey":"username","rangeKey":"timestamp"},{"tableName":"nuscloudca-mobilehub-726174774-AWSMobileTable","attributes":[{"name":"teamId","type":"S"},{"name":"personId","type":"S"},{"name":"email","type":"S"},{"name":"personName","type":"S"},{"name":"phone","type":"S"}],"indexes":[{"indexName":"personName-index","hashKey":"teamId","rangeKey":"personName"}],"region":"ap-southeast-1","hashKey":"teamId","rangeKey":"personId"}],
    'aws_mobile_analytics_app_id': '0c75209b47e646b0b478aa0dc0d7bf1f',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'ed45c688-ce24-4841-bfde-894a5d7645f4',
    'aws_project_name': 'nuscloudca',
    'aws_project_region': 'ap-southeast-1',
    'aws_resource_name_prefix': 'nuscloudca-mobilehub-726174774',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'nuscloudca-userfiles-mobilehub-726174774',
    'aws_user_files_s3_bucket_region': 'ap-southeast-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'ap-southeast-1_N5bxZoMsc',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '3r36m9ir8ccvmr1qsl1m6fq14v',
}

export default awsmobile;
